In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import glob
import os
import sys
from collections import OrderedDict
import seaborn as sns
%matplotlib inline
np.random.seed(1547)


#import blob to make reading of files in easier
%ls

 Volume in drive C is Windows
 Volume Serial Number is 361D-A6A7

 Directory of C:\Users\Don\Desktop\github\DS-1-Data-Analysis

02/18/2018  05:28 PM    <DIR>          .
02/18/2018  05:28 PM    <DIR>          ..
02/05/2018  12:12 PM             8,196 .DS_Store
02/18/2018  05:14 PM    <DIR>          .ipynb_checkpoints
02/05/2018  12:12 PM             1,876 00__Test_Installation.ipynb
02/17/2018  09:36 PM           447,250 01__Descriptive_Statistics.ipynb
02/17/2018  09:35 PM           327,245 02__Data_Visualization.ipynb
02/18/2018  04:19 PM             4,383 03.5__Converting_Z-scores_to_Probability.ipynb
02/18/2018  04:53 PM            74,847 03__Normal_Distribution_and_CLT.ipynb
02/08/2018  02:56 PM             9,984 04_Outlier_Detection_Sample_Size_&_Confidence_Intervals.ipynb
02/17/2018  09:35 PM            90,036 10 Titanic Question and Anwers using DataFrames.ipynb
02/15/2018  11:51 AM    <DIR>          data
02/18/2018  04:43 PM    <DIR>          datasets
02/18/2018  02:06 AM             1,887 HackerRank SQL Challenges.ipynb
02/08/2018  02:56 PM    <DIR>          img
02/05/2018  12:12 PM             8,942 Installation_Instructions.md
02/18/2018  05:28 PM           123,950 Make_School_Data_Analysis_Project .ipynb
02/15/2018  02:30 PM           307,704 Makeschool DS 1 Final Project.ipynb
02/05/2018  12:12 PM               355 README.md
02/18/2018  05:08 PM            29,095 SQL Database Exploration Questions.ipynb
02/17/2018  09:38 PM            24,938 Visualization Practice and Examples.ipynb
              15 File(s)      1,460,688 bytes
               6 Dir(s)  67,351,707,648 bytes free

In [39]:


for name in glob.glob('2017/Student Feedback Surveys-Superview.csv'):
    print (name)

2017/Student Feedback Surveys-Superview.csv

In [40]:
for name in glob.glob('2016/*'):
    print (name)

2016\Anon Week 1 Feedback - LA.csv
2016\Anon Week 1 Feedback - NY.csv
2016\Anon Week 1 Feedback - SF.csv
2016\Anon Week 1 Feedback - Singapore.csv
2016\Anon Week 1 Feedback - SV.csv
2016\Anon Week 2 Feedback - LA.csv
2016\Anon Week 2 Feedback - NY.csv
2016\Anon Week 2 Feedback - SF.csv
2016\Anon Week 2 Feedback - SG.csv
2016\Anon Week 2 Feedback - SV.csv
2016\Anon Week 3 Feedback - LA.csv
2016\Anon Week 3 Feedback - NY.csv
2016\Anon Week 3 Feedback - SF.csv
2016\Anon Week 3 Feedback - SG.csv
2016\Anon Week 3 Feedback - SV.csv
2016\Anon Week 4 Feedback - LA.csv
2016\Anon Week 4 Feedback - NY.csv
2016\Anon Week 4 Feedback - SF.csv
2016\Anon Week 4 Feedback - SG.csv
2016\Anon Week 4 Feedback - SV.csv
2016\Anon Week 5 Feedback - HK.csv
2016\Anon Week 5 Feedback - LA.csv
2016\Anon Week 5 Feedback - NY.csv
2016\Anon Week 5 Feedback - SF.csv
2016\Anon Week 5 Feedback - SG.csv
2016\Anon Week 5 Feedback - SV.csv
2016\Anon Week 6 Feedback - HK.csv
2016\Anon Week 6 Feedback - LA.csv
2016\Anon Week 6 Feedback - NY.csv
2016\Anon Week 6 Feedback - SF.csv
2016\Anon Week 6 Feedback - SG.csv
2016\Anon Week 6 Feedback - SV.csv
2016\Anon Week 6 Feedback - Taipei.csv
2016\Anon Week 6 Feedback - Tokyo.csv
2016\Anon Week 7 Feedback - LA.csv
2016\Anon Week 7 Feedback - NY.csv
2016\Anon Week 7 Feedback - SF.csv
2016\Anon Week 7 Feedback - SV.csv
2016\Anon Week 7 Feedback - Taipei.csv
2016\Week 8 Feedback (2016, incomplete) - results.csv

In [41]:
print(glob.glob('2017/Student Feedback Surveys-Superview.csv'))

['2017/Student Feedback Surveys-Superview.csv']

In [42]:
MS2017_data_df= pd.read_csv('2017/Student Feedback Surveys-Superview.csv')
MS2017_data_df

,ID,Location,Track,Week,Rating (Num),Schedule Pacing
0,134,San Francisco,"Apps, Explorer",Week 1,3,Just right
1,36,Los Angeles,Apps,Week 1,4,A little too fast
2,117,San Francisco,Games,Week 1,4,Way too slow
3,253,NaN,NaN,Week 2,4,A little too fast
4,350,New York City,"Apps, Explorer",Week 1,4,Just right
5,23,Redwood City,Apps,Week 1,5,Just right
6,28,Los Angeles,Apps,Week 7,5,Just right
7,65,San Francisco,Apps,Week 1,5,A little too slow
8,101,Santa Clara,Apps,Week 1,5,A little too slow
9,124,Santa Clara,Apps,Week 1,5,Just right
10,157,Redwood City,Apps,Week 2,5,Just right
11,170,Oakland,Apps,Week 2,5,Just right
12,255,San Francisco,Apps,Week 2,5,Way too fast
13,289,Washington DC,Apps,Week 1,5,Just right
14,299,Washington DC,"Apps, Explorer",Week 1,5,A little too slow
15,307,NaN,NaN,Week 3,5,A little too slow
16,319,Redwood City,Apps,Week 3,5,Just right
17,336,New York City,Apps,Week 1,5,A little too slow
18,441,San Francisco,"Apps, Explorer",Week 3,5,Just right
19,482,Santa Clara,Apps,Week 3,5,Just right
20,37,Los Angeles,Games,Week 1,6,Just right
21,41,Chicago,"Apps, Explorer",Week 1,6,Just right
22,45,Chicago,Apps,Week 1,6,A little too slow
23,47,Chicago,Apps,Week 1,6,A little too slow
24,77,San Francisco,Apps,Week 1,6,A little too fast
25,78,San Francisco,Apps,Week 1,6,A little too fast
26,94,San Francisco,"Apps, Explorer",Week 1,6,Just right
27,193,Santa Clara,Apps,Week 2,6,Just right
28,251,San Francisco,"Apps, Explorer",Week 2,6,Just right
29,254,San Francisco,Apps,Week 2,6,Way too fast
...,...,...,...,...,...,...
1423,1470,New York City,Games,Week 7,10,Just right
1424,1471,New York City,Apps,Week 7,8,Just right
1425,1472,New York City,Games,Week 7,9,Just right
1426,1473,New York City,"Games, Explorer",Week 7,10,Just right
1427,1474,New York City,Games,Week 7,9,Just right
1428,1475,New York City,Apps,Week 7,9,Just right
1429,1476,New York City,Apps,Week 7,8,A little too fast
1430,1477,New York City,Games,Week 7,10,Just right
1431,1478,New York City,Apps,Week 7,10,Just right
1432,1479,New York City,Games,Week 7,9,Just right
1433,1480,New York City,Apps,Week 7,9,Just right
1434,1481,New York City,Apps,Week 7,10,Just right
1435,1482,New York City,Apps,Week 7,8,Just right
1436,1483,New York City,Apps,Week 7,7,A little too fast
1437,1484,New York City,"Apps, Explorer",Week 7,7,Way too fast
1438,1485,New York City,Apps,Week 7,7,Just right
1439,1486,New York City,Apps,Week 7,9,Just right
1440,1487,New York City,Apps,Week 7,8,Just right
1441,1488,New York City,"Games, Explorer",Week 7,7,Just right
1442,1489,New York City,"Apps, Explorer",Week 7,10,Just right
1443,1490,New York City,"Apps, Explorer",Week 7,10,Just right
1444,1491,New York City,Games,Week 7,9,A little too fast
1445,1492,New York City,Apps,Week 7,9,Just right
1446,1493,New York City,Apps,Week 7,3,Just right
1447,1494,New York City,"Games, Explorer",Week 7,10,Just right
1448,1495,New York City,"Apps, Explorer",Week 7,10,Just right
1449,1496,New York City,"Apps, Explorer",Week 7,8,Just right
1450,1497,New York City,Apps,Week 7,10,Just right
1451,1498,New York City,"Apps, Explorer",Week 7,1,A little too slow
1452,1499,New York City,Apps,Week 5,8,Just right

In [43]:
#investigationg head and tail for EOF Errora
MS2017_data_df.head()
MS2017_data_df.tail()

,ID,Location,Track,Week,Rating (Num),Schedule Pacing
1448,1495,New York City,"Apps, Explorer",Week 7,10,Just right
1449,1496,New York City,"Apps, Explorer",Week 7,8,Just right
1450,1497,New York City,Apps,Week 7,10,Just right
1451,1498,New York City,"Apps, Explorer",Week 7,1,A little too slow
1452,1499,New York City,Apps,Week 5,8,Just right

In [ ]:
# Beginning of globbing files for the 2016 folders... T_T;;
#MS2016_data_df= pd.read_csv('2016/Anon Week 7 Feedback - Taipei.csv')
#MS2016_data_df

In [44]:

# will take all of the 2016 files ( yes i know theyre un sorted) and put them into one giant file, as a test for later interations
files = sorted(glob.iglob('2016/*.csv'))
header = OrderedDict()
data = []
for filename in files:
    with open(filename, 'r') as fin:
        csvin = csv.DictReader(fin)
        header.update(OrderedDict.fromkeys(csvin.fieldnames))
        data.append(next(csvin))
with open('output_filename_version2.csv', 'w', newline='') as fout:
    csvout = csv.DictWriter(fout, fieldnames=list(header))
    csvout.writeheader()
    csvout.writerows(data)

In [45]:
# failed attempt but keeping code to frankenstien it in a later interations
MS2016_data_df= pd.read_csv('output_filename_version2.csv')
MS2016_data_df

,Timestamp,How would you rate your overall satisfaction with the Summer Academy this week?,How well are the tutorials paced?,What track are you in?,Unnamed: 4,How well is the schedule paced?,#,How likely is it that you would recommend the Make School Summer Academy to a friend?,location,track,Start Date (UTC),Submit Date (UTC),Network ID
0,6/23/2016 15:55:12,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6/24/2016 7:03:34,3.0,5.0,Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6/24/2016 14:02:56,3.0,2.0,Apps,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2.0,4.0,Games,6/24/2016 13:32:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6/23/2016 22:24:53,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6/30/2016 14:09:14,4.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7/1/2016 6:41:31,3.0,NaN,Apps,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7/1/2016 16:35:14,2.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7/1/2016 5:41:15,4.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7/1/2016 13:27:56,3.0,NaN,Apps,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7/8/2016 10:31:27,4.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,7/8/2016 6:21:11,4.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,7/8/2016 15:56:20,3.0,NaN,Apps,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,7/8/2016 7:36:11,4.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,7/8/2016 12:52:08,5.0,NaN,Games,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7/15/2016 13:20:35,5.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7/15/2016 6:28:26,5.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,7/15/2016 15:26:38,5.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,7/15/2016 2:45:00,4.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,7/15/2016 13:30:19,2.0,NaN,Apps,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,7/21/2016 21:57:59,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,7/22/2016 16:15:37,3.0,NaN,Games,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,7/22/2016 13:29:33,5.0,NaN,Apps,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,3.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,7/22/2016 1:30:17,4.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,7/22/2016 12:52:43,4.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,7/29/2016 0:19:08,5.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,7/31/2016 8:43:57,5.0,NaN,Games,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,7/29/2016 6:54:22,2.0,NaN,Apps,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,7/29/2016 15:17:19,4.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,7/29/2016 19:18:44,4.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,7/29/2016 13:46:28,4.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,7/29/2016 1:07:23,5.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,7/31/2016 1:04:57,3.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,8/5/2016 11:22:50,3.0,NaN,Intro,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,8/5/2016 12:34:16,3.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,8/5/2016 11:13:01,5.0,NaN,Apps,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,8/5/2016 13:37:43,3.0,NaN,Apps,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,8/5/2016 1:39:41,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,00b836bda84e6bdbe780af97e249e59f,10.0,New York,summerApps,9/7/16 1:03,9/7/16 1:04,3212b7a834

In [24]:
#worked with several students to get this corrent and now submitting ( got the most help from jsutin since he's on my core project team,
#figuring out how to get the other cities, singapore might give me the most trouble)

# This was a hard dataset due tpo the fact that the data had to be scraped and cleaned and was not all the same size, 
#nor did it have the same columns, Had help from Kaichi, Justin and Tassos

location = 'datasets/SA Feedback Surveys_FINAL/2016/'

#Get all files in the 2016 folder
filenames = glob.glob(location + 'Anon Week * Feedback - *.csv')

#NOTE: SG IS FOR SINGAPORE-- was confused by that untill i started looking up abbreviations


#week 8 was previously having issues being read and had to be read it its own list


#settign for week 8
eigth_week = glob.glob(location + '*Week 8*')
#reads and addews to the csv files already established, so ti will look like the others
week8_df = pd.read_csv(eigth_week[0])


#List of names of columns scraped from the file names
df_2016 = pd.DataFrame([])
list_2016 = []

#print("FILE COUNT:", len(filenames))

#create week set and city set so there are no duplicate entries, important for the data frame
week_set = set()
city_set = set()

for file_name in filenames:
    rows = list()
    #split on spaces in file name
    file_data = file_name.split(" ")
    week = file_data[2]
    #split on . in file name
    city_list = file_data[-1].split('.')
    city = city_list[0]
    file_df = pd.read_csv(file_name)
    
    week_set.add(week)
    city_set.add(city)
    
    week_data = []
    city_data = []
    #addes the city and week data to the columns rows
    for _ in range(0, len(file_df)):
        week_data.append(week)
        city_data.append(city)
    #finally at the end the file data frames week and city property will have the week and city row data collected and added
    file_df["Week"] = week_data
    file_df["City"] = city_data
    list_2016.append(file_df)
    
clean_2016_df = pd.concat(list_2016)
# testing if it displays correctly
clean_2016_df

,City,How well are the tutorials paced?,How well is the schedule paced?,How would you rate your overall satisfaction with the Summer Academy this week?,Timestamp,Unnamed: 0,Week,What track are you in?
0,LA,4.0,NaN,3,6/23/2016 15:55:12,NaN,Surveys_FINAL/2016\Anon,NaN
1,LA,4.0,NaN,4,6/23/2016 16:14:04,NaN,Surveys_FINAL/2016\Anon,NaN
2,LA,4.0,NaN,4,6/24/2016 0:18:42,NaN,Surveys_FINAL/2016\Anon,NaN
3,LA,4.0,NaN,4,6/24/2016 6:59:42,NaN,Surveys_FINAL/2016\Anon,NaN
4,LA,5.0,NaN,4,6/24/2016 9:40:16,NaN,Surveys_FINAL/2016\Anon,NaN
5,LA,4.0,NaN,5,6/23/2016 22:07:29,NaN,Surveys_FINAL/2016\Anon,NaN
6,LA,3.0,NaN,5,6/24/2016 9:34:14,NaN,Surveys_FINAL/2016\Anon,NaN
0,NY,5.0,NaN,3,6/24/2016 7:03:34,NaN,Surveys_FINAL/2016\Anon,Games
1,NY,3.0,NaN,3,6/24/2016 7:10:22,NaN,Surveys_FINAL/2016\Anon,Games
2,NY,3.0,NaN,3,6/24/2016 7:03:41,NaN,Surveys_FINAL/2016\Anon,Apps
3,NY,3.0,NaN,4,6/24/2016 7:04:59,NaN,Surveys_FINAL/2016\Anon,Intro
4,NY,4.0,NaN,4,6/24/2016 7:07:02,NaN,Surveys_FINAL/2016\Anon,Intro
5,NY,4.0,NaN,4,6/24/2016 7:08:41,NaN,Surveys_FINAL/2016\Anon,Intro
6,NY,4.0,NaN,4,6/24/2016 7:09:30,NaN,Surveys_FINAL/2016\Anon,Intro
7,NY,4.0,NaN,4,6/24/2016 7:01:03,NaN,Surveys_FINAL/2016\Anon,Games
8,NY,4.0,NaN,4,6/24/2016 7:02:43,NaN,Surveys_FINAL/2016\Anon,Games
9,NY,3.0,NaN,4,6/24/2016 7:03:48,NaN,Surveys_FINAL/2016\Anon,Games
10,NY,3.0,NaN,4,6/24/2016 7:06:04,NaN,Surveys_FINAL/2016\Anon,Games
11,NY,4.0,NaN,4,6/24/2016 7:06:24,NaN,Surveys_FINAL/2016\Anon,Games
12,NY,4.0,NaN,4,6/24/2016 7:01:19,NaN,Surveys_FINAL/2016\Anon,Apps
13,NY,4.0,NaN,4,6/24/2016 7:01:29,NaN,Surveys_FINAL/2016\Anon,Apps
14,NY,4.0,NaN,4,6/24/2016 7:02:20,NaN,Surveys_FINAL/2016\Anon,Apps
15,NY,3.0,NaN,4,6/24/2016 7:03:24,NaN,Surveys_FINAL/2016\Anon,Apps
16,NY,4.0,NaN,4,6/24/2016 7:03:25,NaN,Surveys_FINAL/2016\Anon,Apps
17,NY,2.0,NaN,4,6/24/2016 7:03:58,NaN,Surveys_FINAL/2016\Anon,Apps
18,NY,3.0,NaN,4,6/24/2016 7:06:59,NaN,Surveys_FINAL/2016\Anon,Apps
19,NY,4.0,NaN,4,6/24/2016 7:07:06,NaN,Surveys_FINAL/2016\Anon,Apps
20,NY,4.0,NaN,4,6/24/2016 7:08:37,NaN,Surveys_FINAL/2016\Anon,Apps
21,NY,3.0,NaN,4,6/24/2016 7:08:51,NaN,Surveys_FINAL/2016\Anon,Apps
22,NY,3.0,NaN,5,6/24/2016 7:01:55,NaN,Surveys_FINAL/2016\Anon,Intro
...,...,...,...,...,...,...,...,...
28,SV,NaN,5,5,8/5/2016 13:32:40,NaN,Surveys_FINAL/2016\Anon,Games
29,SV,NaN,3,4,8/5/2016 15:07:12,NaN,Surveys_FINAL/2016\Anon,Games
30,SV,NaN,3,4,8/5/2016 13:36:23,NaN,Surveys_FINAL/2016\Anon,Games
31,SV,NaN,3,5,8/5/2016 13:51:20,NaN,Surveys_FINAL/2016\Anon,Games
32,SV,NaN,4,4,8/5/2016 13:39:45,NaN,Surveys_FINAL/2016\Anon,Games
33,SV,NaN,3,5,8/5/2016 14:44:00,NaN,Surveys_FINAL/2016\Anon,Games
34,SV,NaN,3,3,8/5/2016 14:03:39,NaN,Surveys_FINAL/2016\Anon,Games
35,SV,NaN,4,4,8/5/2016 13:47:15,NaN,Surveys_FINAL/2016\Anon,Intro
36,SV,NaN,3,4,8/5/2016 13:45:29,NaN,Surveys_FINAL/2016\Anon,Intro
37,SV,NaN,3,5,8/5/2016 13:49:31,NaN,Surveys_FINAL/2016\Anon,Intro
38,SV,NaN,3,5,8/5/2016 13:47:02,NaN,Surveys_FINAL/2016\Anon,Intro
39,SV,NaN,3,5,8/5/2016 13:48:45,NaN,Surveys_FINAL/2016\Anon,Intro
40,SV,NaN,3,5,8/5/2016 13:44:33,NaN,Surveys_FINAL/2016\Anon,Intro
41,SV,NaN,4,5,8/5/2016 13:43:43,NaN,Surveys_FINAL/2016\Anon,Intro
42,SV,NaN,4,4,8/5/2016 13:44:24,NaN,Surveys_FINAL/2016\Anon,Intro
43,SV,NaN,3,4,8/5/2016 13:43:17,NaN,Surveys_FINAL/2016\Anon,Intro
44,SV,NaN,3,5,8/5/2016 13:51:18,NaN,Surveys_FINAL/2016\Anon,Intro
45,SV,NaN,2,4,8/5/2016 13:43:35,NaN,Surveys_FINAL/2016\Anon,Intro
46,SV,NaN,3,3,8/7/2016 17:45:06,NaN,Surveys_FINAL/2016\Anon,Apps
0,Taipei,NaN,3,3,8/5/2016 1:39:41,NaN,Surveys_FINAL/2016\Anon,NaN
1,Taipei,NaN,3,4,8/5/2016 1:40:47,NaN,Surveys_FINAL/2016\Anon,NaN
2,Taipei,NaN,3,4,8/5/2016 1:40:50,NaN,Surveys_FINAL/2016\Anon,NaN
3,Taipei,NaN,4,4,8/5/2016 1:42:44,NaN,Surveys_FINAL/2016\Anon,NaN
4,Taipei,NaN,4,5,8/5/2016 1:45:13,NaN,Surveys_FINAL/2016\Anon,NaN
5,Taipei,NaN,3,4,8/5/2016 1:45:39,NaN,Surveys_FINAL/2016\Anon,NaN
6,Taipei,NaN,3,4,8/5/2016 1:49:21,NaN,Surveys_FINAL/2016\Anon,NaN
7,Taipei,NaN,3,5,8/8/2016 1:30:34,NaN,Surveys_FINAL/2016\Anon,NaN
8,Taipei,NaN,3,5,8/8/2016 1:33:45,NaN,Surveys_FINAL/2016\Anon,NaN
9,Taipei,NaN,3,5,8/8/2016 1:49:29,NaN,Surveys_FINAL/2016\Anon,NaN
10,Taipei,NaN,3,3,8/8/2016 1:51:00,NaN,Surveys_FINAL/2016\Anon,NaN

In [26]:
clean_2016_df.describe()

       How well are the tutorials paced?
count                         216.000000
mean                            3.384259
std                             0.658068
min                             2.000000
25%                             3.000000
50%                             3.000000
75%                             4.000000
max                             5.000000